// <auto-generated />
using Authentication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Authentication.Migrations
{
    [DbContext(typeof(CadastroContext))]
    [Migration("20180115000951_Alteracao-propertis")]
    partial class Alteracaopropertis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Authentication.Model.UserLogin", b =>
                {
                    b.Property<int>("UserLoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password")
                        .HasMaxLength(16);

                    b.Property<string>("token");

                    b.Property<string>("user")
                        .HasMaxLength(20);

                    b.HasKey("UserLoginId");

                    b.ToTable("login");
                });

            modelBuilder.Entity("Authentication.Model.UserRegister", b =>
                {
                    b.Property<int>("UserRegisterId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dtRegister");

                    b.Property<string>("firstNameUser")
                        .HasMaxLength(15);

                    b.Property<string>("lastNameUser")
                        .HasMaxLength(15);

                    b.Property<string>("password")
                        .HasMaxLength(16);

                    b.Property<string>("token");

                    b.HasKey("UserRegisterId");

                    b.ToTable("register");
                });
#pragma warning restore 612, 618
        }
    }
}
