USE DBCADASTRO
GO

BEGIN TRY
	BEGIN TRANSACTION

		DELETE FROM TBL_ORIGIN_ACCESS

		SET IDENTITY_INSERT dbo.TBL_ORIGIN_ACCESS ON 
		IF NOT EXISTS(SELECT 1 FROM TBL_ORIGIN_ACCESS WHERE DS_ORIGIN = 'FACEBOOK')
		BEGIN
			INSERT INTO [dbo].[tbl_Origin_Access]
					   ([cd_origin_access],[ds_origin])
				 VALUES
					   (1,'FACEBOOK')
		END

		IF NOT EXISTS(SELECT 1 FROM TBL_ORIGIN_ACCESS WHERE DS_ORIGIN = 'APPLICATION')
		BEGIN
			INSERT INTO [dbo].[tbl_Origin_Access]
					   ([cd_origin_access],[ds_origin])
				 VALUES
					   (2,'APPLICATION')
		END
		SET IDENTITY_INSERT dbo.TBL_ORIGIN_ACCESS OFF 
	COMMIT
	PRINT 'COMMIT'
END TRY
BEGIN CATCH
	ROLLBACK
	PRINT 'ROLLBACK'
END CATCH

GO
